Config:
    # service type value in essential, file and metadata
    service-type: pv_puller
    models-loc: https://raw.githubusercontent.com/CBIIT/crdc-datahub-models/
    cde-data-element-api: https://cadsrapi.cancer.gov/rad/NCIAPI/1.0/api/DataElements?publicId=